channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=23.3
- pip:
  - mlflow==2.9.1
  - cloudpickle==3.0.0
  - packaging==23.2
  - psutil==5.9.0
  - pyyaml==6.0.1
  - scikit-learn==1.3.2
  - typing-extensions==4.8.0
name: mlflow-env
